---
tags: [SOAP]
projects: [spring-ws]
---
:spring_version: current
:toc:
:project_id: gs-consuming-web-service
:spring_version: current
:spring_boot_version: 1.0.0.RC4
:icons: font
:source-highlighter: prettify

This guide walks you through the process of creating a "hello world" link:/understanding/SOAP[SOAP-based web service] with Spring.

== What you'll build

You'll build a client that can fetch data from a remote, WSDL-based web service using the http://en.wikipedia.org/wiki/SOAP[SOAP protocol].

----
http://wsf.cdyne.com/WeatherWS/Weather.asmx
----

The service provides weather forecasts and you'll be able to insert your own zip code.


== What you'll need

include::https://raw.github.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]


include::https://raw.github.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


[[scratch]]
== Set up the project

include::https://raw.github.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.github.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]


include::https://raw.github.com/spring-guides/getting-started-macros/master/create_both_builds.adoc[]
`build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::initial/build.gradle[]
----

include::https://raw.github.com/spring-guides/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]


[[initial]]
== Generate domain objects based on a WSDL

The interface to a SOAP-based web service is captured in a http://en.wikipedia.org/wiki/Web_Services_Description_Language[WSDL]. JAX-B2 provides an easy means to generate Java domain objects using this XML specification.

To generate a batch of Java domain objects with maven, you need the following plugin setup:

[source,xml,indent=0]
----
include::complete/pom.xml[tags=wsdl]
----

It sets the target package for each generated class as `hello.wsdl`. It also points at the weather site's WSDL contract.

To do the same with gradle, you can see this in the build file:

[source,java,indent=0]
----
include::complete/build.gradle[tags=wsdl]
----

In gradle, it's a bit more complex because it invokes an ant library to do the processing.

In both cases, the JAX-B2 domain object generation process has been wired into the build tool's lifecycle so there are no extra steps to run.

== Create a weather service client

To create a web service client, you simply have to extend the http://docs.spring.io/spring-ws/sites/2.0/apidocs/org/springframework/ws/client/core/support/WebServiceGatewaySupport.html[WebServiceGatewaySupport] class and code your operations:

`src/main/java/hello/GreetingController.java`
[source,java]
----
include::complete/src/main/java/hello/WeatherClient.java[]
----

In this example, it creates a new request object, `GetCityForecastByZIP`. It then invokes the inherited `WebServiceTemplate` to fire off it's request.

There is a second method use to print the results to the console.

== Configuring web service components

Spring WS uses Spring Framework's OXM module which has the `Jaxb2Marshaller` to serialize and deserialize XML requests.

`src/main/java/hello/WeatherConfiguration.java`
[source,java]
----
include::complete/src/main/java/hello/WeatherConfiguration.java[]
----

The `marshaller` is pointed at the collection of generated domain objects and will use them to both serialize and deserialize between XML and POJOs.

The `weatherClient` is created and configured with the URI of the weather service shown up above. It is also configured to use the JAXB marshaller.

== Make the application executable

This application is packaged up to run from the console and retrieve a single weather forecast for a given zip code.

`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

The `main()` method defers to the http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html[`SpringApplication`] helper class, providing `Application.class` as an argument to its `run()` method. This tells Spring to read the annotation metadata from `Application` and to manage it as a component in the link:/understanding/application-context[Spring application context].

NOTE: This application is hard coded to look up zip code 94304, Palo Alto, CA. Towards the end of this guide, you'll see how to plug in a different zip code without editing the code.

include::https://raw.github.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.github.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]

:module: service
include::https://raw.github.com/spring-guides/getting-started-macros/master/run_the_application_with_both.adoc[]

Logging output is displayed. The service should be up and running within a few seconds.

```
Requesting forecast for 94304

Forecast for Palo Alto, CA
2013-01-03 Partly Cloudy °-57° 
2013-01-04 Partly Cloudy 41°-58° 
2013-01-05 Partly Cloudy 41°-59° 
2013-01-06 Partly Cloudy 44°-56° 
2013-01-07 Partly Cloudy 41°-60° 
2013-01-08 Partly Cloudy 42°-60° 
2013-01-09 Partly Cloudy 43°-58° 
```

You can plug in a different zip code by typing `java -jar build/libs/gs-consuming-web-service-0.1.0.jar 34769`

```
Requesting forecast for 34769

Forecast for Saint Cloud, FL
2014-02-18 Sunny 51°-79° 
2014-02-19 Sunny 55°-81° 
2014-02-20 Sunny 59°-84° 
2014-02-21 Partly Cloudy 63°-85° 
2014-02-22 Partly Cloudy 63°-84° 
2014-02-23 Partly Cloudy 63°-82° 
2014-02-24 Partly Cloudy 62°-80° 
```

== Summary

Congratulations! You've just developed a client to consume a SOAP-based web service with Spring. 




